apiVersion: v1
kind: Service
metadata:
  name: {{ include "wp-stack.fullname" $ }}
  labels:
    app: {{ include "wp-stack.name" . }}
spec:
  selector:
    app: {{ include "wp-stack.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP